"""Add address field to locations table

Revision ID: 65503d41abfb
Revises: 8418ac1154e3
Create Date: 2025-08-19 10:55:04.926660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65503d41abfb'
down_revision = '8418ac1154e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
